totalEpoch: 1200
startEpoch: 1
lr: 0.003
factor: 0.9

lossModel:
  model:
    asn:
      shape: [ 640, 640 ]
    backbone:
      netID: 'b0'
      depthProb: 0.2
      useSE: True
    neck:
      dataPoint: [ 24, 40, 112, 1280 ]
      exp: 256
    head:
      k: 50
      exp: 256

  loss:
    threshScale: 10
    threshLoss:
      eps: !!float '1e-6'
    probScale: 5
    probLoss:
      ratio: 3.
      eps: !!float '1e-6'
    binaryScale: 1
    binaryLoss:
      eps: !!float '1e-6'

score:
  totalBox: 1000
  edgeThresh: 5
  probThresh: 0.3
  scoreThresh: 0.7
  label: 'binaryMap'

accurancy:
  ignoreThresh: 0.5
  scoreThresh: 0.7
  accThresh: 0.5

train:
  batchSize: 8
  numWorkers: 1
  dropLast: True
  shuffle: True
  pinMemory: False
  dataset:
    imgType: 1
    imgDir: 'train/image'
    tarFile: 'target.json'
    prep:
      DetAug:
        onlyResize: False
        Fliplr:
          p: 0.5
        Affine:
          rotate: !!python/tuple [-10, 10]
          shear:
              x: !!python/tuple [ -5, 5 ]
              y: !!python/tuple [ -5, 5 ]
          fit_output: True
        Resize:
          size: !!python/tuple [0.5, 3.]
      DetCrop:
        generalSize: [800, 800]
        minCropSize: 0.1
        maxTries: 10
      DetForm:
        shrinkRatio: 0.4
      ProbMaker:
        shrinkRatio: 0.4
        minTextSize: 8
      ThreshMaker:
        expandRatio: 0.4
        minThresh: 0.3
        maxThresh: 0.7
      DetNorm:
        mean: [ 122.67891434, 116.66876762, 104.00698793 ]
      DetFilter:
        key: [ 'polygon', 'shape', 'ignore', 'train' ]

valid:
  batchSize: 1
  numWorkers: 1
  dropLast: True
  shuffle: False
  pinMemory: False
  dataset:
    imgType: 1
    imgDir: 'valid/image'
    tarFile: 'target.json'
    prep:
      DetAug:
        onlyResize: False
        Fliplr:
          p: 0.5
      DetForm:
        shrinkRatio: 0.4
      ProbMaker:
        shrinkRatio: 0.4
        minTextSize: 8
      ThreshMaker:
        expandRatio: 0.4
        minThresh: 0.3
        maxThresh: 0.7
      DetNorm:
        mean: [ 122.67891434, 116.66876762, 104.00698793 ]
      DetFilter:
        key: [ 'polygon', 'shape', 'ignore', 'train' ]

optimizer:
  name: Adam
  args:
    betas: [ 0.9, 0.999 ]
    eps: !!float '1e-8'

checkpoint:
  workspace: './checkpoint'
  resume: ''

logger:
  workspace: './logger'
  level: INFO
